window.CH16_LESSON_TARGETS = [
  "Define each key term in Alarm in your own words.",
  "Distinguish related concepts within Alarm and apply them to a new scenario.",
  "Define each key term in Confounding variables in your own words.",
  "Distinguish related concepts within Confounding variables and apply them to a new scenario.",
  "Define each key term in Coping with stress in your own words.",
  "Distinguish related concepts within Coping with stress and apply them to a new scenario.",
  "Define each key term in Dependent variables in your own words.",
  "Distinguish related concepts within Dependent variables and apply them to a new scenario.",
  "Define each key term in Exhaustion in your own words.",
  "Distinguish related concepts within Exhaustion and apply them to a new scenario.",
  "Define each key term in Health Effects of Stress in your own words.",
  "Distinguish related concepts within Health Effects of Stress and apply them to a new scenario.",
  "Define each key term in Independent variables in your own words.",
  "Distinguish related concepts within Independent variables and apply them to a new scenario.",
  "Define each key term in Placebo variables in your own words.",
  "Distinguish related concepts within Placebo variables and apply them to a new scenario.",
  "Define each key term in Positive psychology in your own words.",
  "Distinguish related concepts within Positive psychology and apply them to a new scenario.",
  "Define each key term in Psychology and health in your own words.",
  "Distinguish related concepts within Psychology and health and apply them to a new scenario.",
  "Define each key term in Resistance in your own words.",
  "Distinguish related concepts within Resistance and apply them to a new scenario.",
  "Define each key term in Stress and health in your own words.",
  "Distinguish related concepts within Stress and health and apply them to a new scenario.",
  "Define each key term in Stress and immune functioning in your own words.",
  "Distinguish related concepts within Stress and immune functioning and apply them to a new scenario.",
  "Define each key term in Stress basics in your own words.",
  "Distinguish related concepts within Stress basics and apply them to a new scenario.",
  "Define each key term in Sympathetic in your own words.",
  "Distinguish related concepts within Sympathetic and apply them to a new scenario.",
  "Explain how the sections of Chapter 16 connect to the chapter's main ideas."
];
